services:

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_data:/var/jenkins_home

    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions


    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar

  nexus:
    image: sonatype/nexus
    ports:
      - "8081:8081"

    volumes:
      - /opt/nexus/:/var/lib/nexus

  tomcat:
      image: tomee
      ports:
        - "8082:8080"

volumes:
  jenkins_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
